PebbleriteCaveGreenFloors_MapScripts::
	.byte 0

PebbleriteCaveGreenFloors_EventScript_WallTablet1::
	msgbox PebbleriteCaveGreenFloors_Text_WallTablet1, MSGBOX_SIGN
	end

PebbleriteCaveGreenFloors_EventScript_WallTablet2::
	msgbox PebbleriteCaveGreenFloors_Text_WallTablet2, MSGBOX_SIGN
	end

PebbleriteCaveGreenFloors_EventScript_PricklyAura::
	msgbox PebbleriteCaveGreenFloors_Text_PricklyAura, MSGBOX_NPC
	end

PebbleriteCaveGreenFloors_EventScript_Ciphers::
	msgbox PebbleriteCaveGreenFloors_Text_Ciphers, MSGBOX_NPC
	end

PebbleriteCaveGreenFloors_EventScript_CantReadTheTablets::
	msgbox PebbleriteCaveGreenFloors_Text_CantReadTheTablets, MSGBOX_NPC
	end

PebbleriteCaveGreenFloors_EventScript_CaesarSalad::
	msgbox PebbleriteCaveGreenFloors_Text_CaesarSalad, MSGBOX_NPC
	end

PebbleriteCaveGreenFloors_Text_PricklyAura:
	.string "I can't describe it too well but\n"
	.string "to me these glowing pebbles\l"
	.string "have a prickly aura. It's\l"
	.string "like standing in front\l"
	.string "of a dang microwave!$"

PebbleriteCaveGreenFloors_Text_Ciphers:
	.string "You ever hear about something\n"
	.string "called a cipher?\p"
	.string "No, not Team Cipher. Ciphers are\n"
	.string "used as a way to mask secret\l"
	.string "messages by jumbling up and\l"
	.string "switching letters. Once\l"
	.string "you know the cipher used,\l"
	.string "it's possible to decode\l"
	.string "words that look like gibberish.$"

PebbleriteCaveGreenFloors_Text_CantReadTheTablets:
	.string "Maaaaaaannnn...\n"
	.string "I can't read this crud.\p"
	.string "You think you can make\n"
	.string "any sense of this text?\l"
	.string "Be my guest.$"

PebbleriteCaveGreenFloors_Text_CaesarSalad:
	.string "Hey there.\n"
	.string "I'm on my break right now,\l"
	.string "if the boss sent ya.\p"
	.string "Been really chowing down on my\n"
	.string "Caesar Salad.\p"
	.string "...What's so important about it?\n"
	.string "Umm, nothing...?$"

PebbleriteCaveGreenFloors_Text_WallTablet1:
	.string "aol nhyula msvdlyz vm aol thuf\n"
	.string "NLPNLY ayllz vba vm aol dpukvdz\l"
	.string "jvtwsltlua aol zlaapun zbu hz p\l"
	.string "pujyltlua tf JVBUALY mvy khfz\l"
	.string "zwlua pu zahzpz$"

PebbleriteCaveGreenFloors_Text_WallTablet2:
	.string "p mpuk pu tf thuf wopsvzvwopjhs\n"
	.string "YLHKPUNZ aoha aolyl pz GLYV\l"
	.string "huzdly av aol tlhupun vm spml,\l"
	.string "mvy pa pz zabjr pu hu lukslzz\l"
	.string "kvskybtpj jfjsl$"
