#ifndef GUARD_CONSTANTS_BATTLE_TENT_TRAINERS_H
#define GUARD_CONSTANTS_BATTLE_TENT_TRAINERS_H

// CHAMP LEAGUE - TODO
#define BATTLE_TENT_CHAMP_TRAINER_JOLIE    0
#define BATTLE_TENT_CHAMP_TRAINER_MALACHI  1
#define BATTLE_TENT_CHAMP_TRAINER_KELSIE   2

#define NUM_BATTLE_TENT_CHAMP_TRAINERS      3

// MAJOR LEAGUE
#define BATTLE_TENT_MAJOR_TRAINER_BEPIS 0
#define BATTLE_TENT_MAJOR_TRAINER_BRIAR 1
#define BATTLE_TENT_MAJOR_TRAINER_TOADSWORTH 2
#define BATTLE_TENT_MAJOR_TRAINER_HAYLEY 3
#define BATTLE_TENT_MAJOR_TRAINER_DOMINO 4
#define BATTLE_TENT_MAJOR_TRAINER_BARRY 5
#define BATTLE_TENT_MAJOR_TRAINER_ELLA_RATIO 6
#define BATTLE_TENT_MAJOR_TRAINER_EVAN_ROCK 7
#define BATTLE_TENT_MAJOR_TRAINER_KURT 8
#define BATTLE_TENT_MAJOR_TRAINER_SKEETN 9
#define BATTLE_TENT_MAJOR_TRAINER_TRACE 10
#define BATTLE_TENT_MAJOR_TRAINER_COLA 11
#define BATTLE_TENT_MAJOR_TRAINER_JENNY 12
#define BATTLE_TENT_MAJOR_TRAINER_TODD_SNAP 13
#define BATTLE_TENT_MAJOR_TRAINER_YELLOW 14
#define BATTLE_TENT_MAJOR_TRAINER_LI 15
#define BATTLE_TENT_MAJOR_TRAINER_PAUL 16
#define BATTLE_TENT_MAJOR_TRAINER_GAME 17
#define BATTLE_TENT_MAJOR_TRAINER_YUU 18
#define BATTLE_TENT_MAJOR_TRAINER_SURGE 19
#define BATTLE_TENT_MAJOR_TRAINER_ANGELA 20

#define NUM_BATTLE_TENT_MAJOR_TRAINERS      21

// MINOR LEAGUE
#define BATTLE_TENT_MINOR_TRAINER_BEPIS 0
#define BATTLE_TENT_MINOR_TRAINER_BRIAR 1
#define BATTLE_TENT_MINOR_TRAINER_TOADSWORTH 2
#define BATTLE_TENT_MINOR_TRAINER_HAYLEY 3
#define BATTLE_TENT_MINOR_TRAINER_DOMINO 4
#define BATTLE_TENT_MINOR_TRAINER_BARRY 5
#define BATTLE_TENT_MINOR_TRAINER_ELLA_RATIO 6
#define BATTLE_TENT_MINOR_TRAINER_EVAN_ROCK 7
#define BATTLE_TENT_MINOR_TRAINER_KURT 8
#define BATTLE_TENT_MINOR_TRAINER_SKEETN 9
#define BATTLE_TENT_MINOR_TRAINER_TRACE 10
#define BATTLE_TENT_MINOR_TRAINER_COLA 11
#define BATTLE_TENT_MINOR_TRAINER_JENNY 12
#define BATTLE_TENT_MINOR_TRAINER_TODD_SNAP 13
#define BATTLE_TENT_MINOR_TRAINER_YELLOW 14
#define BATTLE_TENT_MINOR_TRAINER_LI 15
#define BATTLE_TENT_MINOR_TRAINER_PAUL 16
#define BATTLE_TENT_MINOR_TRAINER_GAME 17
#define BATTLE_TENT_MINOR_TRAINER_YUU 18
#define BATTLE_TENT_MINOR_TRAINER_SURGE 19
#define BATTLE_TENT_MINOR_TRAINER_ANGELA 20

#define NUM_BATTLE_TENT_MINOR_TRAINERS      21

#define VERDANTURF_TENT_TRAINER_BRENNA  0
#define VERDANTURF_TENT_TRAINER_DILAN   1
#define VERDANTURF_TENT_TRAINER_P_MICYCLEANA  2
#define VERDANTURF_TENT_TRAINER_P_HOTHUS  3
#define VERDANTURF_TENT_TRAINER_CAITLYN 4
#define VERDANTURF_TENT_TRAINER_DESIREE 5
#define VERDANTURF_TENT_TRAINER_P_LULU  6
#define VERDANTURF_TENT_TRAINER_ASHTEN  7
#define VERDANTURF_TENT_TRAINER_GERARD  8
#define VERDANTURF_TENT_TRAINER_BRADLY  9
#define VERDANTURF_TENT_TRAINER_DENNIS  10
#define VERDANTURF_TENT_TRAINER_PRESTIN 11
#define VERDANTURF_TENT_TRAINER_ERNESTO 12
#define VERDANTURF_TENT_TRAINER_NALA    13
#define VERDANTURF_TENT_TRAINER_DARNELL 14
#define VERDANTURF_TENT_TRAINER_ASHLYN  15
#define VERDANTURF_TENT_TRAINER_ADDISON 16
#define VERDANTURF_TENT_TRAINER_P_NINOE 17
#define VERDANTURF_TENT_TRAINER_TYSON   18
#define VERDANTURF_TENT_TRAINER_LAILA   19
#define VERDANTURF_TENT_TRAINER_WAREN   20
#define VERDANTURF_TENT_TRAINER_TOBIAS  21
#define VERDANTURF_TENT_TRAINER_JOSIAH  22
#define VERDANTURF_TENT_TRAINER_DION    23
#define VERDANTURF_TENT_TRAINER_KENZIE  24
#define VERDANTURF_TENT_TRAINER_LILLIAN 25
#define VERDANTURF_TENT_TRAINER_LESLEY  26
#define VERDANTURF_TENT_TRAINER_MARQUIS 27
#define VERDANTURF_TENT_TRAINER_FREDDY  28
#define VERDANTURF_TENT_TRAINER_CECILIA 29

#define FALLARBOR_TENT_TRAINER_AMBER    0
#define FALLARBOR_TENT_TRAINER_JAVIER   1
#define FALLARBOR_TENT_TRAINER_NATALIA  2
#define FALLARBOR_TENT_TRAINER_TREVE    3
#define FALLARBOR_TENT_TRAINER_ARIANNA  4
#define FALLARBOR_TENT_TRAINER_JADYN    5
#define FALLARBOR_TENT_TRAINER_GERARDO  6
#define FALLARBOR_TENT_TRAINER_JONN     7
#define FALLARBOR_TENT_TRAINER_ESTEBAN  8
#define FALLARBOR_TENT_TRAINER_JAMESON  9
#define FALLARBOR_TENT_TRAINER_P_UNSELDZO   10
#define FALLARBOR_TENT_TRAINER_HOWARD   11
#define FALLARBOR_TENT_TRAINER_CONRAD   12
#define FALLARBOR_TENT_TRAINER_MAKENNA  13
#define FALLARBOR_TENT_TRAINER_BRAYAN   14
#define FALLARBOR_TENT_TRAINER_MARIANA  15
#define FALLARBOR_TENT_TRAINER_SHELDON  16
#define FALLARBOR_TENT_TRAINER_GIANNA   17
#define FALLARBOR_TENT_TRAINER_YAHIR    18
#define FALLARBOR_TENT_TRAINER_BRITNEY  19
#define FALLARBOR_TENT_TRAINER_HECTER   20
#define FALLARBOR_TENT_TRAINER_TANNOR   21
#define FALLARBOR_TENT_TRAINER_P_MCKAYLEIGHJI    22
#define FALLARBOR_TENT_TRAINER_RORY     23
#define FALLARBOR_TENT_TRAINER_ELEANOR  24
#define FALLARBOR_TENT_TRAINER_EVELYN   25
#define FALLARBOR_TENT_TRAINER_ARIELLE  26
#define FALLARBOR_TENT_TRAINER_CONNAR   27
#define FALLARBOR_TENT_TRAINER_MAURICE  28
#define FALLARBOR_TENT_TRAINER_KIANNA   29

#define NUM_BATTLE_TENT_TRAINERS 30

#endif  // GUARD_CONSTANTS_BATTLE_TENT_TRAINERS_H
